#!/bin/bash

if [ ! -e 0-preprocessor ]; then
    echo "File 0-preprocessor is not present"
    exit 1
fi

if [ ! -s README.md ]; then
    echo "README.md does not exist or is empty"
    exit 1
fi

line_count=$(wc -l < 0-preprocessor)

if [ "$line_count" -ne 2 ]; then
    echo "File 0-preprocessor contains $line_count lines, it should be 2"
    exit 1
fi

first_line=$(head -n 1 0-preprocessor)

if [ "$first_line" != "#!/bin/bash" ]; then
    echo "First line of 0-preprocessor does not contain #!/bin/bash"
    exit 1
fi

CFILE=$CFILE
OUTPUT_FILE="c"

cpp -P $CFILE | sed '/^$/d; /^#/d; s/\/\*.*\*\///g; s/\/\/.*//g' > $OUTPUT_FILE

tail $OUTPUT_FILE

